### ISSUE TITLE
脚本运行时命令行黑框显示一瞬间后关闭，未能成功运行

### ISSUE THREAD

**Issue by tianyeMedicago** [CXRunfree/Autovisor#15]
如题，系统win11，电脑自带的edge路径是C:\Program Files (x86)\Microsoft\Edge\Application，已确认uri和账号密码无误

**Comment by CXRunfree** [comment]
你是否运行的是源代码？如果是，可以在cmd中输入python Autovisor.py查看报错原因，猜测可能是没导入依赖库playwright

**Comment by tianyeMedicago** [comment]
我运行的是封装的

**Comment by tianyeMedicago** [comment]
Traceback (most recent call last):
  File "Autovisor.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "res\configs.py", line 6, in <module>
    _config.read('account.ini')
  File "configparser.py", line 698, in read
  File "configparser.py", line 1097, in _read
configparser.DuplicateOptionError: While reading from 'account.ini' [line 16]: option 'https' in section 'course-url' already exists
[6808] Failed to execute script 'Autovisor' due to unhandled exception!

**Comment by CXRunfree** [comment]
网址格式不太对，换行之后最左边要加个空格

**Comment by tianyeMedicago** [comment]
好我试试看

**Comment by tianyeMedicago** [comment]
解决了，非常感谢
