### ISSUE TITLE
浏览器刷新崩溃

### ISSUE THREAD

**Issue by 1302557841** [CXRunfree/Autovisor#20]
Traceback (most recent call last):
  File "Autovisor.py", line 232, in <module>
  File "Autovisor.py", line 218, in main_function
  File "Autovisor.py", line 145, in start_course_loop
  File "Autovisor.py", line 57, in optimize_page
  File "playwright\sync_api\_generated.py", line 2110, in click
  File "playwright\_impl\_sync_base.py", line 115, in _sync
  File "playwright\_impl\_element_handle.py", line 137, in click
  File "playwright\_impl\_connection.py", line 63, in send
  File "playwright\_impl\_connection.py", line 495, in wrap_api_call
  File "playwright\_impl\_connection.py", line 101, in inner_send
playwright._impl._errors.Error: Element is not attached to the DOM

**Comment by CXRunfree** [comment]
是你手动刷新导致的吗? 还是程序自己切换页面导致的
