### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by psno** [CXRunfree/Autovisor#24]
log.txt:
---
Traceback (most recent call last):
  File "Autovisor.py", line 303, in <module>
  File "Autovisor.py", line 289, in main_function
  File "Autovisor.py", line 183, in learning_loop
  File "res\process.py", line 31, in get_progress
TypeError: get_progress.<locals>.parse_time() missing 2 required positional arguments: 'm' and 's'
---
之后便一直不能自动输入账号及密码并且手动输入会自动刷新

**Comment by CXRunfree** [comment]
请确认各项配置信息是否填写正确, 另外多重启几次试试
