### ISSUE TITLE
最新发行版3.14.1运行到课程页面闪退

### ISSUE THREAD

**Issue by Nethtra** [CXRunfree/Autovisor#30]
回退到上个版本3.13.1没出现这个问题

**Comment by CXRunfree** [comment]
发一下报错信息,或者配置信息及闪退界面的截图

**Comment by Nethtra** [comment]
刚打开到课程界面就会闪退，大约在这个位置，浏览器和命令窗口一起闪退，看不到信息，用的是edge 128.0.2739.79 (正式版本) (64 位)
![image](https://github.com/user-attachments/assets/a117199f-80d3-4d24-94f5-f9b909c6973f)
先用上一个版本了

**Comment by nuclear06** [comment]
在登录完加载播放界面是出现闪退
os: ubuntu 22.04
browser: chrome
```
Traceback (most recent call last):
  File "/home/user/Autovisor/Autovisor.py", line 219, in entrance
    await optimize_page(page, config)
  File "/home/user/Autovisor/res/utils.py", line 17, in optimize_page
    await page.evaluate(config.no_hint)
  File "/home/user/.virtualenvs/Autovisor-emul/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 8689, in evaluate
    await self._impl_obj.evaluate(
  File "/home/user/.virtualenvs/Autovisor-emul/lib/python3.10/site-packages/playwright/_impl/_page.py", line 400, in evaluate
    return await self._main_frame.evaluate(expression, arg)
  File "/home/user/.virtualenvs/Autovisor-emul/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 282, in evaluate
    await self._channel.send(
  File "/home/user/.virtualenvs/Autovisor-emul/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 63, in send
    return await self._connection.wrap_api_call(
  File "/home/user/.virtualenvs/Autovisor-emul/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 495, in wrap_api_call
    return await cb()
  File "/home/user/.virtualenvs/Autovisor-emul/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 101, in inner_send
    result = next(iter(done)).result()
playwright._impl._errors.Error: TypeError: Cannot read properties of null (reading 'click')
    at eval (eval at evaluate (:226:30), <anonymous>:1:41)
    at eval (<anonymous>)
    at UtilityScript.evaluate (<anonymous>:226:30)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
```

**Comment by CXRunfree** [comment]
已经推出fixed-3.14.1版本, 该问题已经得到修复.你可以下载尝试一下

**Comment by Nethtra** [comment]
帅
