### ISSUE TITLE
3.13.1在前缀为https://fusioncourseh5.zhihuishu.com/stuStudy/index?recruitAndCourseId=的课程内无法使用

### ISSUE THREAD

**Issue by Mendax114514** [CXRunfree/Autovisor#31]
课程视频可以正常加载，加载之后网页疑似刷新了然后edge浏览器崩溃
报错如下
Traceback (most recent call last):
  File "Autovisor.py", line 303, in <module>
  File "Autovisor.py", line 284, in main_function
  File "Autovisor.py", line 49, in optimize_page
  File "playwright\sync_api\_generated.py", line 8725, in evaluate
  File "playwright\_impl\_sync_base.py", line 115, in _sync
  File "playwright\_impl\_page.py", line 400, in evaluate
  File "playwright\_impl\_frame.py", line 282, in evaluate
  File "playwright\_impl\_connection.py", line 63, in send
  File "playwright\_impl\_connection.py", line 495, in wrap_api_call
  File "playwright\_impl\_connection.py", line 101, in inner_send
playwright._impl._errors.Error: TypeError: Cannot read properties of undefined (reading 'click')
    at eval (eval at evaluate (:226:30), <anonymous>:1:58)
    at eval (<anonymous>)
    at UtilityScript.evaluate (<anonymous>:226:30)
    at UtilityScript.<anonymous> (<anonymous>:1:44)

**Comment by CXRunfree** [comment]
以fusioncourseh5开头代表智慧共享课，是智慧树新推出的界面，目前脚本没有适配。

**Comment by CXRunfree** [comment]
目前在3.15.2版本解除了这个限制, 你可以试一试
