### ISSUE TITLE
fix   show_course_progress函数中参数错误使用

### ISSUE THREAD

**Issue by 0AyanamiRei** [CXRunfree/Autovisor#60]
```
[15:21:00] [INFO] 正在学习:0.1.、绪论
[15:21:02] [ERROR] AttributeError("'float' object has no attribute 'split'")
[15:21:02] Traceback (most recent call last):
  File "XXXXXXXXX\Autovisor\Autovisor\Autovisor.py", line 196, in main
    await working_loop(page, is_new_version=is_new_version)
  File "XXXXXXXXX\Autovisor\Autovisor\Autovisor.py", line 131, in working_loop
    await review_loop(page, start_time)
  File "XXXXXXXXX\Autovisor\Autovisor\Autovisor.py", line 98, in review_loop
    show_course_progress(desc="完成进度:", cur_time=time_period, limit_time=limit_time)
  File "XXXXXXXXX\Autovisor\Autovisor\modules\progress.py", line 49, in show_course_progress
    percent = int(cur_time.split("%")[0]) + 1  # Handles a 1% rendering error
                  ^^^^^^^^^^^^^^
AttributeError: 'float' object has no attribute 'split'
```
根据日志应该是`progress.py`组件, 函数`show_course_progress`中的参数类型的错误, https://github.com/CXRunfree/Autovisor/blob/main/modules/progress.py :
```python
def show_course_progress(desc, cur_time=None, limit_time=0):
    assert limit_time >= 0, "limit_time 必须为非负数!"
    if limit_time == 0:
        cur_time = "0%" if cur_time == '' else cur_time
        percent = int(cur_time.split("%")[0]) + 1  # Handles a 1% rendering error
....
```
这里的`cur_time`应该是float类型的, 目前可以通过设置 `limit_time`不为0, 或者修改上面的代码为:
```python
def show_course_progress(desc, cur_time=None, limit_time=0):
    assert limit_time >= 0, "limit_time 必须为非负数!"
    if limit_time == 0:
        cur_time = 0 if cur_time == '' else cur_time
        percent = int(cur_time * 10) + 1  # Handles a 1% rendering error
        # print(percent, "   ",cur_time * 10)
.....
```
就可以正常使用了

**Comment by 0AyanamiRei** [comment]
该错误貌似只会出现在某门课的完成率大于80的情况，还有一个办法在配置文件里手动删除该URL的链接
