### ISSUE TITLE
在完成第一节课后切换课程报错，程序自动退出

### ISSUE THREAD

**Issue by aeuicey** [CXRunfree/Autovisor#61]
使用“URL1 URL2”表示的队列课程。实测切换课程时会出现报错（第一节已完成）
下面是程序日志：
`[06:34:47] [INFO] 程序启动中...
[06:34:47] [INFO] 开始下载依赖库...
[06:34:47] [INFO] numpy-1.26.4 已安装！
[06:34:47] [INFO] opencv-python-4.10.0.82 已安装！
[06:34:47] [INFO] 所有依赖库下载完成!
[06:34:49] [INFO] 正在启动edge浏览器...
[06:34:50] edge浏览器启动完成.
[06:34:50] stealth.js注入完成.
[06:34:50] 窗口大小设置完成.
[06:34:50] [INFO] 正在等待登录完成...
[06:34:53] [INFO] 第1次尝试过滑块验证...
[06:34:53] [WARN] 检测到安全验证,请手动完成验证...
[06:34:55] [INFO] 滑块验证已成功通过.
[06:34:55] [INFO] 安全验证已完成.
[06:34:55] [INFO] 正在加载播放页...
[06:34:58] Exec JS failed: document.querySelector(".exploreTip").remove(); Selector:1500 Error:Error('Page.wait_for_selector: selector: expected string, got number')
[06:34:58] Traceback (most recent call last):
  File "modules\utils.py", line 15, in evaluate_js
  File "playwright\async_api\_generated.py", line 7994, in wait_for_selector
  File "playwright\_impl\_page.py", line 397, in wait_for_selector
  File "playwright\_impl\_frame.py", line 323, in wait_for_selector
  File "playwright\_impl\_connection.py", line 59, in send
  File "playwright\_impl\_connection.py", line 514, in wrap_api_call
playwright._impl._errors.Error: Page.wait_for_selector: selector: expected string, got number
[06:34:58] [INFO] 页面优化完成!
[06:34:58] [INFO] 当前课程:<<地球历史及其生命的奥秘>>
[06:34:59] [INFO] 检测到视频暂停,正在尝试播放.
[06:34:59] 视频已恢复播放.
[06:34:59] Get to-learn class: 127
[06:34:59] Get to-review class: 127
[06:35:00] [INFO] 检测到视频暂停,正在尝试播放.
[06:35:00] 视频已恢复播放.
[06:35:01] [INFO] 正在学习:1.1.1、古老的美好神话
[06:35:01] [ERROR] AttributeError("'float' object has no attribute 'split'")
[06:35:01] Traceback (most recent call last):
  File "Autovisor.py", line 196, in main
  File "Autovisor.py", line 131, in working_loop
  File "Autovisor.py", line 98, in review_loop
  File "modules\progress.py", line 49, in show_course_progress
AttributeError: 'float' object has no attribute 'split'
[06:35:01] 浏览器已关闭,视频调节模块已下线.
[06:35:01] 浏览器已关闭,答题模块已下线.
[06:35:01] 浏览器已关闭,视频播放模块已下线.
[06:35:28] 浏览器已关闭,安全验证模块已下线.
`

**Comment by CXRunfree** [comment]
3.17.1版本已修复
