### ISSUE TITLE
Edge&&智慧共享课无法播放视频&&附log

### ISSUE THREAD

**Issue by Maaolin** [CXRunfree/Autovisor#69]
资源里面第一项是PPT，后台一直检测到视频暂停，正在尝试播放，也无法跳转
日志：
[12:50:23] [INFO] 程序启动中...
[12:50:24] [INFO] 正在启动edge浏览器...
[12:50:25] edge浏览器启动完成.
[12:50:25] stealth.js注入完成.
[12:50:25] 窗口大小设置完成.
[12:50:25] [INFO] 正在等待登录完成...
[12:50:28] [WARN] 检测到安全验证,请手动完成验证...
[12:50:28] [INFO] 安全验证已完成.
[12:50:31] [INFO] 正在加载播放页...
[12:50:34] [INFO] 检测到视频暂停,正在尝试播放.
[12:50:36] [INFO] 检测到视频暂停,正在尝试播放.
[12:50:38] [INFO] 检测到视频暂停,正在尝试播放.
[12:50:40] [INFO] 检测到视频暂停,正在尝试播放.
[12:50:42] [INFO] 检测到视频暂停,正在尝试播放.
[12:50:46] [INFO] 检测到视频暂停,正在尝试播放.
[12:50:48] [INFO] 检测到视频暂停,正在尝试播放.
[12:50:50] [INFO] 检测到视频暂停,正在尝试播放.
[12:50:51] Exec JS failed: document.getElementsByClassName("iconfont iconguanbi")[0].click(); Selector:.studytime-div Error:TargetClosedError('Page.wait_for_selector: Target page, context or browser has been closed\nCall log:\nwaiting for locator(".studytime-div") to be visible\n')
[12:50:51] Traceback (most recent call last):
  File "modules\utils.py", line 15, in evaluate_js
  File "playwright\async_api\_generated.py", line 7994, in wait_for_selector
  File "playwright\_impl\_page.py", line 397, in wait_for_selector
  File "playwright\_impl\_frame.py", line 323, in wait_for_selector
  File "playwright\_impl\_connection.py", line 59, in send
  File "playwright\_impl\_connection.py", line 514, in wrap_api_call
playwright._impl._errors.TargetClosedError: Page.wait_for_selector: Target page, context or browser has been closed
Call log:
waiting for locator(".studytime-div") to be visible

[12:50:51] 浏览器已关闭,视频播放模块已下线.
[12:50:51] 浏览器已关闭,答题模块已下线.
[12:50:51] Exec JS failed: document.getElementsByClassName("ai-show-icon ai-icon-appear")[0].remove(); Selector:.ai-show-icon.ai-icon-appear Error:TargetClosedError('Page.wait_for_selector: Target page, context or browser has been closed')
[12:50:51] Traceback (most recent call last):
  File "modules\utils.py", line 15, in evaluate_js
  File "playwright\async_api\_generated.py", line 7994, in wait_for_selector
  File "playwright\_impl\_page.py", line 397, in wait_for_selector
  File "playwright\_impl\_frame.py", line 323, in wait_for_selector
  File "playwright\_impl\_connection.py", line 59, in send
  File "playwright\_impl\_connection.py", line 514, in wrap_api_call
playwright._impl._errors.TargetClosedError: Page.wait_for_selector: Target page, context or browser has been closed
[12:50:51] Exec optimize_page failed. Error:TargetClosedError('Page.wait_for_selector: Target page, context or browser has been closed')
[12:50:51] Traceback (most recent call last):
  File "modules\utils.py", line 32, in optimize_page
  File "playwright\async_api\_generated.py", line 7994, in wait_for_selector
  File "playwright\_impl\_page.py", line 397, in wait_for_selector
  File "playwright\_impl\_frame.py", line 323, in wait_for_selector
  File "playwright\_impl\_connection.py", line 59, in send
  File "playwright\_impl\_connection.py", line 514, in wrap_api_call
playwright._impl._errors.TargetClosedError: Page.wait_for_selector: Target page, context or browser has been closed
[12:50:51] [INFO] 页面优化完成!
[12:50:51] [ERROR] TargetClosedError('Page.wait_for_selector: Target page, context or browser has been closed')
[12:50:51] Traceback (most recent call last):
  File "Autovisor.py", line 192, in main
  File "playwright\async_api\_generated.py", line 7994, in wait_for_selector
  File "playwright\_impl\_page.py", line 397, in wait_for_selector
  File "playwright\_impl\_frame.py", line 323, in wait_for_selector
  File "playwright\_impl\_connection.py", line 59, in send
  File "playwright\_impl\_connection.py", line 514, in wrap_api_call
playwright._impl._errors.TargetClosedError: Page.wait_for_selector: Target page, context or browser has been closed
[12:50:51] [ERROR] 浏览器被关闭,程序退出.
[12:50:52] 浏览器已关闭,视频调节模块已下线.
[12:51:01] 浏览器已关闭,安全验证模块已下线.

**Comment by CXRunfree** [comment]
那就是不支持这种页面，毕竟没办法对所有网址都做适配☹️
